server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://dpg-cq7gnp2ju9rs73a5r1j0-a:5432/prototipo_ecommerce
    password: JCJ7ZB8Z5zykBzjcevBadf73MfLWFNcC
    username: prototipo_ecommerce_user